### ISSUE TITLE
Doesn´t work on simulator

### ISSUE THREAD

**Issue by angelelectrico** [codenameone/cn1-codescan#2]
I get a NPE while trying:

            final CodeScanner codeScanner = CodeScanner.getInstance();
            codeScanner.scanQRCode(result);

The codeScanner is null... is this expected?
Thanks!

**Comment by shannah** [comment]
The CodeScanner isn't supported currently in the simulator.  Call CodeScanner.isSupported() before trying to use it to ensure that it is supported by the current platform.
