### ISSUE TITLE
In Android device sends request to install Barcode Scanner

### ISSUE THREAD

**Issue by angelelectrico** [codenameone/cn1-codescan#3]
In Android device pops up a request for installing the Barcode Scanner which does not have any action buttons and does halt the app...

Here is the screen shot.
[http://s29.postimg.org/4b0nq4kmf/Screenshot_2016_03_01_10_41_54.png](url)

Thank you!

**Comment by shannah** [comment]
@chen-fishbein The codescanner code is basically the same as the old core codescanner.  Do you know if there are any build hints required for the barcode scanner to work?

**Comment by chen-fishbein** [comment]
No there aren't any build hints.
The blank dialog is because he is running without a theme.

**Comment by shannah** [comment]
@chen-fishbein So is it normal that the user would be prompted to install BarCodeScanner?

**Comment by chen-fishbein** [comment]
yes

**Comment by shannah** [comment]
OK.  Closing this issue then.

**Comment by angelelectrico** [comment]
So is the code scanner an external app that needs installing?
